// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Domain.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "e9c7412a-5932-45f7-bac9-0338e753115f",
                            Description = "Hong Kong speciality is lemon tea - served in cafes and restaurants as regular black tea with several slices of fresh lemon, either hot or cold, with a pot of sugar to add to taste.",
                            IsDeleted = false,
                            Title = "Lemon Tea"
                        },
                        new
                        {
                            Id = "10c2da38-cf19-44ef-a926-645a6efb4a90",
                            Description = "Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain flowering plants in the Coffea genus. From the coffee fruit, the seeds are separated to produce a stable, raw product: unroasted green coffee.",
                            IsDeleted = false,
                            Title = "Coffee"
                        },
                        new
                        {
                            Id = "5da4aad5-666f-46e5-adb3-7b787cd3ea0e",
                            Description = "Hot chocolate, also known as hot cocoa or drinking chocolate, is heated chocolate milk. Hot chocolate made with melted chocolate is sometimes called drinking chocolate, characterized by less sweetness and a thicker consistency.",
                            IsDeleted = false,
                            Title = "Hot chocolate"
                        });
                });

            modelBuilder.Entity("Domain.RecipeMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMethods");

                    b.HasData(
                        new
                        {
                            Id = "d7e1be09-6ab2-4c44-b9c3-8864bf8a84d1",
                            Description = "Boil some water",
                            IsDeleted = false,
                            Optional = false,
                            Order = 1,
                            RecipeId = "2e12f26b-d06e-47f2-8d00-d5b316fc8abc"
                        },
                        new
                        {
                            Id = "f6435fa2-86eb-4db1-ac96-7579829b2ad9",
                            Description = "Steep the water in the tea",
                            IsDeleted = false,
                            Optional = false,
                            Order = 2,
                            RecipeId = "2e12f26b-d06e-47f2-8d00-d5b316fc8abc"
                        },
                        new
                        {
                            Id = "f852d95c-b682-4db0-958d-2a4c8796d770",
                            Description = "Pour tea in the cup",
                            IsDeleted = false,
                            Optional = false,
                            Order = 3,
                            RecipeId = "2e12f26b-d06e-47f2-8d00-d5b316fc8abc"
                        },
                        new
                        {
                            Id = "20c61f1a-19e1-4faf-a284-5db76fa03343",
                            Description = "Add lemon",
                            IsDeleted = false,
                            Optional = false,
                            Order = 4,
                            RecipeId = "2e12f26b-d06e-47f2-8d00-d5b316fc8abc"
                        });
                });

            modelBuilder.Entity("Domain.RecipeMethod", b =>
                {
                    b.HasOne("Domain.Recipe", null)
                        .WithMany("RecipeMethod")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Recipe", b =>
                {
                    b.Navigation("RecipeMethod");
                });
#pragma warning restore 612, 618
        }
    }
}
